# Generated by Django 4.2.4 on 2023-09-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoderDos', '0004_estudiantes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaDeEntrega', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('profesion', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Profesores',
        ),
    ]
